apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-app
  template:
    metadata:
      labels:
        app: kubernetes-app
    spec:
      containers:
      - name: kubernetes-app
        image: cerebro31/nodekube-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app-service
spec:
  selector:
    app: kubernetes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
